
<section class="inner-header">
    <div class="container">
        <div class="row">
            <div class="col-md-12 sec-title colored text-center">
                <h2><?= $this->translate('Register') ?></h2>
                <ul class="breadcumb">
                    <li><a href="index.html"><?= $this->translate('Home') ?></a></li>
                    <li><i class="fa fa-angle-right"></i></li>
                    <li><span><?= $this->translate('Register') ?></span></li>
                </ul>
                <span class="decor"><span class="inner"></span></span>
            </div>
        </div>
    </div>
</section>

<section class="sec-padding donation-section">
    <div class="container">
        <h2 class="text-thm"><?= $this->translate('Register') ?></h2>
        <hr>
        <div class="form-outer">
            
            <?= $this->partial('/application/partial/form.phtml'); ?>
            
        </div>
    </div>
</section>
