<section class="inner-header">
    <div class="container">
        <div class="row">
            <div class="col-md-12 sec-title colored text-center">
                <h2><?= $this->translate('Manage Players') ?></h2>
                <ul class="breadcumb">
                    <li><a href="/"><?= $this->translate('Home') ?></a></li>
                    <li><i class="fa fa-angle-right"></i></li>
                    <li><a href="/application/manage/index"><?= $this->translate('Administration') ?></a></li>
                    <li><i class="fa fa-angle-right"></i></li>
                    <li><span><?= $this->translate('Manage Players') ?></span></li>
                </ul>
                <span class="decor"><span class="inner"></span></span>
            </div>
        </div>
    </div>
</section>

<section class="sec-padding donation-section">
    <div class="container">
        <h2 class="text-thm"><?= $this->translate('Manage Players') ?></h2>
        <hr>
        <div class="form-outer">
            <div class="table-responsive">
                <table class="table table-condensed table-hover">
                    <thead>
                        <tr>
                            <th><?= $this->translate('ID') ?></th>
                            <th><?= $this->translate('Pseudo') ?></th>
                            <th><?= $this->translate('Role') ?></th>
                            <th><?= $this->translate('Points') ?></th>
                            <th><?= $this->translate('Votes') ?></th>
                            <th><?= $this->translate('Actions') ?></th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($this->players as $player): ?>
                            <tr>
                                <td><?= $player->getId() ?></td>
                                <td><?= $player->getPseudo() ?></td>
                                <td><?= $player->getRole() ?></td>
                                <td><?= $player->getPoints() ?></td>
                                <td><?= $player->getVotes() ?></td>
                                <td>
                                    <div class="btn-group btn-group-xs">
                                        <a class="btn btn-default"
                                           href="/application/player/edit/<?php $player->getId() ?>">
                                            <?= $this->translate('Edit') ?>
                                        </a>
                                        <a class="btn btn-warning"
                                           href="/application/player/ban/<?php $player->getId() ?>">
                                            <?= $this->translate('Ban') ?>
                                        </a>
                                        <a class="btn btn-danger"
                                           href="/application/player/delete/<?php $player->getId() ?>">
                                            <?= $this->translate('Delete') ?>
                                        </a>
                                    </div>
                                </td>
                            </tr>
                        <?php endforeach; ?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</section>
