<?= $this->doctype(); ?>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <?=
                $this->headTitle($this->translate('Empire Minecraft'))
                ->setSeparator(' - ')
                ->setAutoEscape(false)
        ?>

        <?=
                $this->headMeta()
                ->appendName('viewport', 'width=device-width, initial-scale=1.0')
                ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ;
        ?>

        <!-- Le styles -->
        <?=
                $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/assets/img/logo.png'))
                ->appendStylesheet($this->basePath('/assets/css/style.css'))
                ->appendStylesheet($this->basePath('/assets/css/responsive.css'))
                ->appendStylesheet($this->basePath('/assets/css/bootstrap-margin-padding.css'))
                ->appendStylesheet($this->basePath('/assets/css/jquery.growl.css'))
        ;
        ?>

        <!-- Scripts -->
        <?=
                $this->headScript()
                ->appendFile($this->basePath('assets/js/jquery-1.11.1.min.js'))
                ->appendFile($this->basePath('assets/js/bootstrap.min.js'))
                ->appendFile($this->basePath('assets/js/jquery-ui-1.11.4/jquery-ui.js'))
        ;
        ?>
    </head>
    <body>
        <header class="header">
            <div class="container">
                <div class="logo pull-left">
                    <a href="/">
                        <img alt="Empire Minecraft"
                             src="<?= $this->basePath('/assets/images/resources/logo.png') ?>" />
                    </a>
                </div>
                <div class="header-right-info pull-right clearfix">
                    <div class="single-header-info">
                        <div class="icon-box">
                            <div class="inner-box">
                                <i class="flaticon-interface-2"></i>
                            </div>
                        </div>
                        <div class="content">
                            <h3><?= $this->translate('EMAIL') ?></h3>
                            <p>companyname@mail.com</p>
                        </div>
                    </div>
                    <div class="single-header-info">
                        <div class="icon-box">
                            <div class="inner-box">
                                <i class="flaticon-telephone"></i>
                            </div>
                        </div>
                        <div class="content">
                            <h3><?= $this->translate('Call Now') ?></h3>
                            <p><b>(732) 803-010-03</b></p>
                        </div>
                    </div>
                </div>
            </div>
        </header> <!-- /.header -->

        <nav class="mainmenu-area stricky">
            <div class="container">
                <div class="row">
                    <div class="col-xs-12 col-sm-12 col-lg-2 col-md-12">
                        <div class="donate-btn clearfix">

                            <a class="thm-btn pull-left" data-toggle="modal" href="#modal-donate-now">
                                <?= $this->translate('Join Us') ?>
                            </a>

                            <div class="nav-footer pull-right">
                                <button><i class="fa fa-bars"></i></button>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-10 col-md-12 col-sm-12 col-xs-12">
                        <div class="navigation">
                            <div class="nav-header">
                                <?=
                                        $this->navigation('navigation')->menu()
                                        ->setAddClassToListItem(true)
                                        ->setMinDepth(0)
                                        ->setMaxDepth(1);
                                ?>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </nav> <!-- /.mainmenu-area -->

        <?= $this->content; ?>

        <!--Footer Section-->
        <footer class="footer sec-padding">
            <div class="container">
                <div class="row">
                    <div class="col-sm-6 col-md-3">
                        <div class="footer-widget about-widget">
                            <a href="#">
                                <img alt="Empire Minecraft"
                                     src="<?= $this->basePath('/assets/images/resources/logo.png') ?>" />
                            </a>
                            <p>Lorem ipsum dolor sit amet, eu me evert laboramus, iudico </p>
                            <ul class="contact">
                                <li><i class="fa fa-map-marker"></i> <span>60 Grant Ave. Carteret NJ 0708</span></li>
                                <li><i class="fa fa-phone"></i> <span>(880) 1723801729</span></li>
                                <li><i class="fa fa-envelope-o"></i> <span>example@gmail.com</span></li>
                            </ul>
                            <ul class="social">
                                <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                                <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                                <li><a href="#"><i class="fa fa-google-plus"></i></a></li>
                                <li><a href="#"><i class="fa fa-pinterest"></i></a></li>
                                <li><a href="#"><i class="fa fa-youtube"></i></a></li>
                            </ul>
                        </div>
                    </div>
                    <div class="col-sm-6 col-md-2">
                        <div class="footer-widget quick-links">
                            <h3 class="title">Pages</h3>
                            <ul>
                                <li><a href="about.html">About Us</a></li>
                                <li><a href="causes-grid.html">Causes</a></li>
                                <li><a href="events-grid.html">Events</a></li>
                                <li><a href="faq.html">Faq</a></li>
                                <li><a href="blog-style-two.html">Archives</a></li>
                                <li><a href="blog-style-one.html">News</a></li>
                                <li><a href="contact.html">Contact</a></li>
                            </ul>
                        </div>
                    </div>
                    <div class="col-sm-6 col-md-4">
                        <div class="footer-widget contact-widget">
                            <h3 class="title">Contact Form</h3>
                            <form action="http://wp1.themexlab.com/html/charity-village/inc/sendemail.php" class="contact-form" id="footer-cf">
                                <input type="text" name="name"  placeholder="Full Name">
                                <input type="text" name="email" placeholder="Email Address" >
                                <textarea name="message" placeholder="Your Message"></textarea>
                                <button type="submit">Send</button>
                            </form>
                        </div>
                    </div>
                    <div class="col-sm-6 latest-post col-md-3">
                        <div class="footer-widget latest-post">
                            <h3 class="title">Latest News</h3>
                            <ul>
                                <li>
                                    <span class="border"></span>
                                    <div class="content">
                                        <a href="blog-details.html">If you need a crown or lorem an implant you will pay it </a>
                                        <span>July 2, 2014</span>
                                    </div>
                                </li>
                                <li>
                                    <span class="border"></span>
                                    <div class="content">
                                        <a href="blog-details.html">If you need a crown or lorem an implant you will pay it </a>
                                        <span>July 2, 2014</span>
                                    </div>
                                </li>
                                <li>
                                    <span class="border"></span>
                                    <div class="content">
                                        <a href="blog-details.html">If you need a crown or lorem an implant you will pay it </a>
                                        <span>July 2, 2014</span>
                                    </div>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </footer>

        <section class="footer-bottom">
            <div class="container text-center">
                <p>
                    &copy; 2005 - <?= date('Y') ?>
                    <?= $this->translate('by') ?> Presteus Sparkling.
                    <?= $this->translate('All rights reserved.') ?>
                </p>
            </div>
        </section>

        <!--Scroll to top-->
        <div class="scroll-to-top"><span class="fa fa-arrow-up"></span></div>

        <?= $this->partial('layout/notifier.phtml') ?>

        <?=
                $this->inlineScript()
                ->appendFile($this->basePath('assets/js/jquery.bxslider.min.js'))
                ->appendFile($this->basePath('assets/js/owl.carousel.min.js'))
                ->appendFile($this->basePath('assets/js/jquery-parallax.js'))
                ->appendFile($this->basePath('assets/js/validate.js'))
                ->appendFile($this->basePath('assets/js/jquery.mixitup.min.js'))
                ->appendFile($this->basePath('assets/js/jquery.fancybox.pack.js'))
                ->appendFile($this->basePath('assets/js/jquery.easing.min.js'))
                ->appendFile($this->basePath('assets/js/circle-progress.js'))
                ->appendFile($this->basePath('assets/js/jquery.appear.js'))
                ->appendFile($this->basePath('assets/js/jquery.countTo.js'))
                ->appendFile('http://maps.google.com/maps/api/js?sensor=true')
                ->appendFile($this->basePath('assets/js/gmap.js'))
                ->appendFile($this->basePath('assets/js/isotope.pkgd.min.js'))
                ->appendFile($this->basePath('assets/revolution/js/jquery.themepunch.tools.min.js'))
                ->appendFile($this->basePath('assets/revolution/js/jquery.themepunch.revolution.min.js'))
                ->appendFile($this->basePath('assets/revolution/js/extensions/revolution.extension.actions.min.js'))
                ->appendFile($this->basePath('assets/revolution/js/extensions/revolution.extension.carousel.min.js'))
                ->appendFile($this->basePath('assets/revolution/js/extensions/revolution.extension.kenburn.min.js'))
                ->appendFile($this->basePath('assets/revolution/js/extensions/revolution.extension.layeranimation.min.js'))
                ->appendFile($this->basePath('assets/revolution/js/extensions/revolution.extension.migration.min.js'))
                ->appendFile($this->basePath('assets/revolution/js/extensions/revolution.extension.navigation.min.js'))
                ->appendFile($this->basePath('assets/revolution/js/extensions/revolution.extension.parallax.min.js'))
                ->appendFile($this->basePath('assets/revolution/js/extensions/revolution.extension.slideanims.min.js'))
                ->appendFile($this->basePath('assets/revolution/js/extensions/revolution.extension.video.min.js'))
                ->appendFile($this->basePath('assets/js/jquery.growl.js'))
                ->appendFile($this->basePath('assets/js/custom.js'))
        ?>
    </body>
</html>