
<!--Rev Slider Wrapper Column-->
<section class="rev_slider_wrapper bannercontainer">
    <div id="slider1" class="rev_slider"  data-version="5.0">
        <ul>

            <!-- SLIDE 1 -->
            <li data-index="rs-1" data-transition="random" data-slotamount="7"  data-easein="default" data-easeout="default" data-masterspeed="1000"  data-thumb="/assets/images/bg/2.jpg"  data-rotate="0"  data-fstransition="fade" data-fsmasterspeed="1500" data-fsslotamount="7" data-saveperformance="off"  data-title="Intro" data-description="">
                <!-- MAIN IMAGE -->
                <img src="/assets/images/bg/2.jpg"  alt=""  data-bgposition="50% 90%" data-bgfit="cover" data-bgrepeat="no-repeat" class="rev-slidebg" data-no-retina>
                <!-- LAYERS -->

                <!-- LAYER NR. 1 -->
                <div class="tp-caption tp-resizeme rs-parallaxlevel-0 text-uppercase"
                     id="rs-1-layer-1"

                     data-x="['left','left','left','left']" 
                     data-hoffset="['370','50','30','17']" 
                     data-y="['center','center','center','center']" 
                     data-voffset="['10','110','180','160']" 
                     data-fontsize="['105','100','70','60']"
                     data-lineheight="['100','90','60','60']"
                     data-width="['none','none','none','400']"
                     data-height="none"
                     data-whitespace="['nowrap','nowrap','nowrap','normal']"
                     data-transform_idle="o:1;"
                     data-transform_in="y:[100%];z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;opacity:0;s:1500;e:Power3.easeInOut;" 
                     data-transform_out="y:[100%];s:1000;e:Power2.easeInOut;s:1000;e:Power2.easeInOut;" 
                     data-mask_in="x:0px;y:[100%];" 
                     data-mask_out="x:inherit;y:inherit;" 
                     data-start="500" 
                     data-splitin="none" 
                     data-splitout="none" 
                     data-basealign="slide" 
                     data-responsive_offset="on"
                     style="z-index: 6; white-space: nowrap;"><span class="text-thm">Care a </span><span class="text-white">Child </span>
                </div>

                <!-- LAYER NR. 2 -->
                <div class="tp-caption BigBold-SubTitle tp-resizeme rs-parallaxlevel-0"
                     id="rs-1-layer-2"

                     data-x="['left','left','left','left']"
                     data-hoffset="['370','55','33','20']" 
                     data-y="['bottom','bottom','bottom','bottom']" 
                     data-voffset="['260','1','74','58']" 
                     data-fontsize="['15','15','15','13']"
                     data-lineheight="['24','24','24','20']"
                     data-width="['570','570','410','280']"
                     data-height="['60','100','100','100']"
                     data-whitespace="normal"
                     data-transform_idle="o:1;"
                     data-transform_in="y:[100%];z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;opacity:0;s:1500;e:Power3.easeInOut;" 
                     data-transform_out="y:50px;opacity:0;s:1000;e:Power2.easeInOut;s:1000;e:Power2.easeInOut;" 
                     data-start="650" 
                     data-splitin="none" 
                     data-splitout="none" 
                     data-basealign="slide" 
                     data-responsive_offset="on"
                     style="z-index: 7; min-width: 570px; max-width: 570px; max-width: 60px; max-width: 60px; white-space: normal;"><span class="text-white">A Premium Revolution Slider Template Lorem ipsum dolor sit amet, consectetur adipisicing. </span>
                </div>

                <!-- LAYER NR. 3 -->
                <div class="tp-caption btn btn-default btn-lg thm-btn pl-40 pr-40 rs-parallaxlevel-0"

                     id="rs-1-layer-3"
                     data-x="['left','left','left','left']" 
                     data-hoffset="['370','480','30','20']" 
                     data-y="['bottom','bottom','bottom','bottom']" 
                     data-voffset="['212','0','30','20']" 
                     data-width="none"
                     data-height="none"
                     data-whitespace="nowrap"
                     data-transform_idle="o:1;"
                     data-transform_in="y:[100%];z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;opacity:0;s:1500;e:Power3.easeInOut;" 
                     data-transform_out="y:50px;opacity:0;s:1000;e:Power2.easeInOut;s:1000;e:Power2.easeInOut;" 
                     data-start="650" 
                     data-splitin="none" 
                     data-splitout="none" 
                     data-actions='[{"event":"click","action":"scrollbelow","offset":"px"}]'
                     data-basealign="slide" 
                     data-responsive_offset="on"
                     style="z-index: 8; white-space: nowrap;;outline:none;box-shadow:none;box-sizing:border-box;-moz-box-sizing:border-box;-webkit-box-sizing:border-box;">DONATE NOW
                </div>

                <!-- LAYER NR. 4 -->
                <div class="tp-caption btn btn-default btn-lg thm-btn inverse pl-40 pr-40 rs-parallaxlevel-0"

                     id="rs-1-layer-4"
                     data-x="['left','left','left','left']" 
                     data-hoffset="['590','480','30','20']" 
                     data-y="['bottom','bottom','bottom','bottom']" 
                     data-voffset="['212','0','30','20']" 
                     data-width="none"
                     data-height="none"
                     data-whitespace="nowrap"
                     data-transform_idle="o:1;"
                     data-transform_in="y:[100%];z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;opacity:0;s:1500;e:Power3.easeInOut;" 
                     data-transform_out="y:50px;opacity:0;s:1000;e:Power2.easeInOut;s:1000;e:Power2.easeInOut;" 
                     data-start="650" 
                     data-splitin="none" 
                     data-splitout="none" 
                     data-actions='[{"event":"click","action":"scrollbelow","offset":"px"}]'
                     data-basealign="slide" 
                     data-responsive_offset="on"
                     style="z-index: 8; white-space: nowrap;outline:none;box-shadow:none;box-sizing:border-box;-moz-box-sizing:border-box;-webkit-box-sizing:border-box;">READ MORE
                </div>

            </li>

            <!-- SLIDE 2 -->
            <li data-index="rs-2" data-transition="random" data-slotamount="7"  data-easein="default" data-easeout="default" data-masterspeed="1000"  data-thumb="/assets/images/bg/3.jpg"  data-rotate="0"  data-fstransition="fade" data-fsmasterspeed="1500" data-fsslotamount="7" data-saveperformance="off"  data-title="Intro" data-description="">
                <!-- MAIN IMAGE -->
                <img src="/assets/images/bg/3.jpg"  alt=""  data-bgposition="center center" data-bgfit="cover" data-bgrepeat="no-repeat" class="rev-slidebg" data-no-retina>
                <!-- LAYERS -->

                <!-- LAYER NR. 1 -->
                <div class="tp-caption tp-resizeme rs-parallaxlevel-0 text-uppercase"
                     id="rs-2-layer-1"

                     data-x="['left','left','left','left']" 
                     data-hoffset="['370','200','30','17']"
                     data-y="['center','center','center','center']" 
                     data-voffset="['10','110','180','160']"
                     data-fontsize="['78']"
                     data-lineheight="['60']"
                     data-width="['none','none','none','400']"
                     data-height="none"
                     data-whitespace="['nowrap','nowrap','nowrap','normal']"
                     data-transform_idle="o:1;"
                     data-transform_in="y:[100%];z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;opacity:0;s:1500;e:Power3.easeInOut;" 
                     data-transform_out="y:[100%];s:1000;e:Power2.easeInOut;s:1000;e:Power2.easeInOut;" 
                     data-mask_in="x:0px;y:[100%];" 
                     data-mask_out="x:inherit;y:inherit;" 
                     data-start="500" 
                     data-splitin="none" 
                     data-splitout="none" 
                     data-basealign="slide" 
                     data-responsive_offset="on"
                     style="z-index: 6; white-space: nowrap;"><span class="text-thm">SAVE</span> <span class="text-white">THE CHILDREN</span>
                </div>

                <!-- LAYER NR. 2 -->
                <div class="tp-caption BigBold-SubTitle tp-resizeme text-white rs-parallaxlevel-0"
                     id="rs-2-layer-2"

                     data-x="['left','left','left','left']"
                     data-hoffset="['370','55','33','20']" 
                     data-y="['bottom','bottom','bottom','bottom']" 
                     data-voffset="['260','1','74','58']"
                     data-fontsize="['15','15','15','13']"
                     data-lineheight="['24','24','24','20']"
                     data-width="['570','570','410','280']"
                     data-height="['60','100','100','100']"
                     data-whitespace="normal"
                     data-transform_idle="o:1;"
                     data-transform_in="y:[100%];z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;opacity:0;s:1500;e:Power3.easeInOut;" 
                     data-transform_out="y:50px;opacity:0;s:1000;e:Power2.easeInOut;s:1000;e:Power2.easeInOut;" 
                     data-start="650" 
                     data-splitin="none" 
                     data-splitout="none" 
                     data-basealign="slide" 
                     data-responsive_offset="on"
                     style="z-index: 7; min-width: 570px; max-width: 570px; max-width: 60px; max-width: 60px; white-space: normal;">A Premium Revolution Slider Template Lorem dolor sit amet, consectetur adipisicing. 
                </div>

                <!-- LAYER NR. 3 -->
                <div class="tp-caption btn btn-default btn-lg thm-btn pl-40 pr-40 rs-parallaxlevel-0"

                     id="rs-2-layer-3"
                     data-x="['left','left','left','left']" 
                     data-hoffset="['370','480','30','20']" 
                     data-y="['bottom','bottom','bottom','bottom']" 
                     data-voffset="['212','0','30','20']" 
                     data-width="none"
                     data-height="none"
                     data-whitespace="nowrap"
                     data-transform_idle="o:1;"
                     data-transform_in="y:[100%];z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;opacity:0;s:1500;e:Power3.easeInOut;" 
                     data-transform_out="y:50px;opacity:0;s:1000;e:Power2.easeInOut;s:1000;e:Power2.easeInOut;" 
                     data-start="650" 
                     data-splitin="none" 
                     data-splitout="none" 
                     data-actions='[{"event":"click","action":"scrollbelow","offset":"px"}]'
                     data-basealign="slide" 
                     data-responsive_offset="on"
                     style="z-index: 8; white-space: nowrap;;outline:none;box-shadow:none;box-sizing:border-box;-moz-box-sizing:border-box;-webkit-box-sizing:border-box;">DONATE NOW
                </div>

                <!-- LAYER NR. 4 -->
                <div class="tp-caption btn btn-default btn-lg thm-btn inverse pl-40 pr-40 rs-parallaxlevel-0"

                     id="rs-2-layer-4"
                     data-x="['left','left','left','left']" 
                     data-hoffset="['590','480','30','20']" 
                     data-y="['bottom','bottom','bottom','bottom']" 
                     data-voffset="['212','0','30','20']" 
                     data-width="none"
                     data-height="none"
                     data-whitespace="nowrap"
                     data-transform_idle="o:1;"
                     data-transform_in="y:[100%];z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;opacity:0;s:1500;e:Power3.easeInOut;" 
                     data-transform_out="y:50px;opacity:0;s:1000;e:Power2.easeInOut;s:1000;e:Power2.easeInOut;" 
                     data-start="650" 
                     data-splitin="none" 
                     data-splitout="none" 
                     data-actions='[{"event":"click","action":"scrollbelow","offset":"px"}]'
                     data-basealign="slide" 
                     data-responsive_offset="on"
                     style="z-index: 8; white-space: nowrap;outline:none;box-shadow:none;box-sizing:border-box;-moz-box-sizing:border-box;-webkit-box-sizing:border-box;">READ MORE
                </div>

            </li>

            <!-- SLIDE 3 -->
            <li data-index="rs-3" data-transition="random" data-slotamount="7"  data-easein="default" data-easeout="default" data-masterspeed="1000"  data-thumb="/assets/images/bg/4.jpg"  data-rotate="0"  data-fstransition="fade" data-fsmasterspeed="1500" data-fsslotamount="7" data-saveperformance="off"  data-title="Intro" data-description="">
                <!-- MAIN IMAGE -->
                <img src="/assets/images/bg/4.jpg"  alt=""  data-bgposition="top center" data-bgfit="cover" data-bgrepeat="no-repeat" class="rev-slidebg" data-no-retina>
                <!-- LAYERS -->

                <!-- LAYER 3 NR. 1 -->
                <div class="tp-caption tp-resizeme text-white rs-parallaxlevel-0"
                     id="rs-3-layer-1"

                     data-x="['left','left','left','left']"
                     data-hoffset="['370','50','30','17']" 
                     data-y="['center','center','center','center']" 
                     data-voffset="['10','110','180','160']" 
                     data-fontsize="['110','100','70','60']"
                     data-lineheight="['100','90','60','60']"
                     data-width="['none','none','none','400']"
                     data-height="none"
                     data-whitespace="['nowrap','nowrap','nowrap','normal']"
                     data-transform_idle="o:1;"
                     data-transform_in="y:[100%];z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;opacity:0;s:1500;e:Power3.easeInOut;" 
                     data-transform_out="y:[100%];s:1000;e:Power2.easeInOut;s:1000;e:Power2.easeInOut;" 
                     data-mask_in="x:0px;y:[100%];" 
                     data-mask_out="x:inherit;y:inherit;" 
                     data-start="500" 
                     data-splitin="none" 
                     data-splitout="none" 
                     data-basealign="slide" 
                     data-responsive_offset="on"
                     style="z-index: 6; white-space: nowrap;"><span class="text-thm">DONATE</span> US
                </div>

                <!-- LAYER 3 NR. 2 -->
                <div class="tp-caption BigBold-SubTitle tp-resizeme text-white rs-parallaxlevel-0"
                     id="rs-3-layer-2"

                     data-x="['left','left','left','left']"
                     data-hoffset="['370','55','33','20']" 
                     data-y="['bottom','bottom','bottom','bottom']" 
                     data-voffset="['260','1','74','58']" 
                     data-fontsize="['15','15','15','13']"
                     data-lineheight="['24','24','24','20']"
                     data-width="['570','570','410','280']"
                     data-height="['60','100','100','100']"
                     data-whitespace="normal"
                     data-transform_idle="o:1;"
                     data-transform_in="y:[100%];z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;opacity:0;s:1500;e:Power3.easeInOut;" 
                     data-transform_out="y:50px;opacity:0;s:1000;e:Power2.easeInOut;s:1000;e:Power2.easeInOut;" 
                     data-start="650" 
                     data-splitin="none" 
                     data-splitout="none" 
                     data-basealign="slide" 
                     data-responsive_offset="on"
                     style="z-index: 7; min-width: 570px; max-width: 570px; max-width: 60px; max-width: 60px; white-space: normal;">A Premium Revolution Slider Template ipsum dolor sit amet, consectetur adipisicing. 
                </div>

                <!-- LAYER 3 NR. 3 -->
                <div class="tp-caption btn btn-default btn-lg thm-btn pl-40 pr-40 rs-parallaxlevel-0"

                     id="rs-3-layer-3"
                     data-x="['left','left','left','left']" 
                     data-hoffset="['370','480','30','20']" 
                     data-y="['bottom','bottom','bottom','bottom']" 
                     data-voffset="['212','0','30','20']" 
                     data-width="none"
                     data-height="none"
                     data-whitespace="nowrap"
                     data-transform_idle="o:1;"
                     data-transform_in="y:[100%];z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;opacity:0;s:1500;e:Power3.easeInOut;" 
                     data-transform_out="y:50px;opacity:0;s:1000;e:Power2.easeInOut;s:1000;e:Power2.easeInOut;" 
                     data-start="650" 
                     data-splitin="none" 
                     data-splitout="none" 
                     data-actions='[{"event":"click","action":"scrollbelow","offset":"px"}]'
                     data-basealign="slide" 
                     data-responsive_offset="on"
                     style="z-index: 8; white-space: nowrap;;outline:none;box-shadow:none;box-sizing:border-box;-moz-box-sizing:border-box;-webkit-box-sizing:border-box;">DONATE NOW
                </div>

                <!-- LAYER 3 NR. 4 -->
                <div class="tp-caption btn btn-default btn-lg thm-btn inverse pl-40 pr-40 rs-parallaxlevel-0"

                     id="rs-3-layer-4"
                     data-x="['left','left','left','left']" 
                     data-hoffset="['590','480','30','20']" 
                     data-y="['bottom','bottom','bottom','bottom']" 
                     data-voffset="['212','0','30','20']" 
                     data-width="none"
                     data-height="none"
                     data-whitespace="nowrap"
                     data-transform_idle="o:1;"
                     data-transform_in="y:[100%];z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;opacity:0;s:1500;e:Power3.easeInOut;" 
                     data-transform_out="y:50px;opacity:0;s:1000;e:Power2.easeInOut;s:1000;e:Power2.easeInOut;" 
                     data-start="650" 
                     data-splitin="none" 
                     data-splitout="none" 
                     data-actions='[{"event":"click","action":"scrollbelow","offset":"px"}]'
                     data-basealign="slide" 
                     data-responsive_offset="on"
                     style="z-index: 8; white-space: nowrap;outline:none;box-shadow:none;box-sizing:border-box;-moz-box-sizing:border-box;-webkit-box-sizing:border-box;">READ MORE
                </div>

            </li>
        </ul>
    </div>
</section>

<!--Featured Three Column-->
<section class="featured-three-column mt-sm-70 pb-50">
    <div class="container">
        <div class="row clearfix">

            <!--Column-->
            <div class="col-xs-12 col-sm-6 col-md-4 column wow fadeInLeft" data-wow-delay="200ms" data-wow-duration="1500ms">
                <article class="inner-box dark-overlay" style="background-image: url(/assets/images/features/1.jpg);">
                    <div class="content">
                        <h3>Donation</h3>
                        <div class="text">
                            <p>Proin nec lacus lacus. Sed vitae consectetur est, et mattis felis. Fusce lacinia nibh vitae fermentum finibus. Donec malesuada efficitur dapibus. Cras euismod nunc tellus, eget tempor purus.</p>
                        </div>
                        <div class="link"><a href="#donation-form" class="thm-btn inverse"><i class="fa fa-caret-right text-text-thmed"></i> Donate Now</a></div>
                    </div>
                </article>
            </div>

            <!--Column-->
            <div class="col-xs-12 col-sm-6 col-md-4 column wow fadeInUp" data-wow-delay="700ms" data-wow-duration="1500ms">
                <article class="inner-box" style="background-image: url(/assets/images/features/2.jpg);">
                    <div class="content">
                        <h3>Volunteer</h3>
                        <div class="text">
                            <p>Proin nec lacus lacus. Sed vitae consectetur est, et mattis felis. Fusce lacinia nibh vitae fermentum finibus. Donec malesuada efficitur dapibus. Cras euismod nunc tellus, eget tempor purus.</p>
                        </div>
                        <div class="link"><a href="#" class="read-more thm-btn normal-btn"><span class="fa fa-caret-right"></span> Join Now</a></div>
                    </div>
                </article>
            </div>

            <!--Column-->
            <div class="col-xs-12 col-sm-6 col-md-4 column wow fadeInRight" data-wow-delay="200ms" data-wow-duration="1500ms">
                <article class="inner-box dark-overlay" style="background-image: url(/assets/images/features/3.jpg);">
                    <div class="content">
                        <h3>Event</h3>
                        <div class="text">
                            <p>Proin nec lacus lacus. Sed vitae consectetur est, et mattis felis. Fusce lacinia nibh vitae fermentum finibus. Donec malesuada efficitur dapibus. Cras euismod nunc tellus, eget tempor purus.</p>
                        </div>
                        <div class="link"><a href="#" class="thm-btn inverse"><i class="fa fa-caret-right text-text-thmed"></i> Read More</a></div>
                    </div>
                </article>
            </div>

        </div>
    </div>
</section>

<!--Start Our Recent Causes Areas-->
<section class="pt-60 pb-50">
    <div class="container">
        <div class="sec-title text-center">
            <div class="row">
                <div class="col-md-6 col-md-offset-3">
                    <span class="double-line"></span> &ensp; <h2>Recent Causes</h2> &ensp; <span class="double-line"></span>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sit!</p>
                </div>
            </div>
        </div>
        <div class="sec-title">
            <div class="row">
                <div class="col-xs-12 col-sm-6 col-md-4 col-lg-4">
                    <div class="recent-causes">
                        <div class="thumb">
                            <img class="img-responsive img-fullwidth" src="/assets/images/causes/1.jpg" alt="">
                        </div>
                        <div class="causes-details">
                            <div class="round-style"></div>
                            <div class="donate-piechart">
                                <div class="piechart-block">
                                    <div class="piechart style-one"  data-fg-color="rgba(136,196,255,1)" data-value=".75">
                                        <span>.75</span>
                                    </div>
                                </div>
                            </div>
                            <h4 class="title">Sponsor a child today</h4>
                            <p class="details pt-5">Lorem ipsum dolor sit amet, consectetur adipisicing. Odit qui minima praesentium illo obcaecati...</p>
                            <ul class="list-inline mb-0 pb-20 clearfix">
                                <li class="causes-raised">Raised: $1890</li>
                                <li class="causes-goal text-thm">Goal: $2500</li>
                            </ul>
                            <a href="#donation-form" class="thm-btn btn-xs"><i class="fa fa-angle-double-right text-white"></i> Donate Now</a>
                            <a class="thm-btn inverse btn-xs" href="#"><i class="fa fa-heart text-text-thmed"></i> 25 Donators</a>
                        </div>
                    </div>
                </div>
                <div class="col-xs-12 col-sm-6 col-md-4 col-lg-4">
                    <div class="recent-causes">
                        <div class="thumb">
                            <img class="img-responsive img-fullwidth" src="/assets/images/causes/2.jpg" alt="">
                        </div>
                        <div class="causes-details">
                            <div class="round-style"></div>
                            <div class="donate-piechart">
                                <div class="piechart-block">
                                    <div class="piechart style-one"  data-fg-color="rgba(136,196,255,1)" data-value=".75">
                                        <span>.75</span>
                                    </div>
                                </div>
                            </div>
                            <h4 class="title">Sponsor a child today</h4>
                            <p class="details pt-5">Lorem ipsum dolor sit amet, consectetur adipisicing. Odit qui minima praesentium illo obcaecati...</p>
                            <ul class="list-inline mb-0 pb-20 clearfix">
                                <li class="causes-raised">Raised: $1890</li>
                                <li class="causes-goal text-thm">Goal: $2500</li>
                            </ul>
                            <a href="#donation-form" class="thm-btn btn-xs"><i class="fa fa-angle-double-right text-white"></i> Donate Now</a>
                            <a class="thm-btn inverse btn-xs" href="#"><i class="fa fa-heart text-text-thmed"></i> 25 Donators</a>
                        </div>
                    </div>
                </div>
                <div class="col-xs-12 col-sm-6 col-md-4 col-lg-4">
                    <div class="recent-causes">
                        <div class="thumb">
                            <img class="img-responsive img-fullwidth" src="/assets/images/causes/3.jpg" alt="">
                        </div>
                        <div class="causes-details">
                            <div class="round-style"></div>
                            <div class="donate-piechart">
                                <div class="piechart-block">
                                    <div class="piechart style-one"  data-fg-color="rgba(136,196,255,1)" data-value=".75">
                                        <span>.75</span>
                                    </div>
                                </div>
                            </div>
                            <h4 class="title">Sponsor a child today</h4>
                            <p class="details pt-5">Lorem ipsum dolor sit amet, consectetur adipisicing. Odit qui minima praesentium illo obcaecati...</p>
                            <ul class="list-inline mb-0 pb-20 clearfix">
                                <li class="causes-raised">Raised: $1890</li>
                                <li class="causes-goal text-thm">Goal: $2500</li>
                            </ul>
                            <a href="#donation-form" class="thm-btn btn-xs"><i class="fa fa-angle-double-right text-white"></i> Donate Now</a>
                            <a class="thm-btn inverse btn-xs" href="#"><i class="fa fa-heart text-text-thmed"></i> 25 Donators</a>
                        </div>
                    </div>
                </div>
            </div>				
        </div>
    </div>
</section>

<!--Start Divider Funfact Area-->
<section class="fact-counter-wrapper sec-padding parallax-section bg-thm">
    <div class="container">
        <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                <div class="charity-info">
                    <!--Start Single charity info-->
                    <div class="col-xs-12 col-sm-6 col-md-3 sm-text-left">
                        <div class="single-charity-info pb-sm-30">
                            <div class="fix charity-count-white alignleft">
                                <h1 class="timer text-white" data-from="1" data-to="350" data-speed="5000" data-refresh-interval="50">350</h1>
                            </div>
                            <div class="fix charity-text pl-20">
                                <p class="text-white">Total Awards</p>
                            </div>
                        </div>
                    </div>
                    <!--Start Single charity info-->
                    <div class="col-xs-12 col-sm-6 col-md-3 sm-text-left">
                        <div class="single-charity-info pb-sm-30">
                            <div class="fix charity-count-white alignleft">
                                <h1 class="timer text-white" data-from="10" data-to="3150" data-speed="5000" data-refresh-interval="50">3150</h1>
                            </div>
                            <div class="fix charity-text pl-20">
                                <p class="text-white">Total Volunteer</p>
                            </div>
                        </div>
                    </div>
                    <!--Start Single charity info-->
                    <div class="col-xs-12 col-sm-6 col-md-3 sm-text-left">
                        <div class="single-charity-info pb-sm-30">
                            <div class="fix charity-count-white alignleft">
                                <h1 class="timer text-white" data-from="10" data-to="1220" data-speed="5000" data-refresh-interval="50">1220</h1>
                            </div>
                            <div class="fix charity-text pl-20">
                                <p class="text-white">Total Projects</p>
                            </div>
                        </div>
                    </div>   
                    <!--Start Single charity info-->
                    <div class="col-xs-12 col-sm-6 col-md-3 sm-text-left">
                        <div class="single-charity-info pb-sm-30">
                            <div class="fix charity-count-white alignleft">
                                <h1 class="timer text-white" data-from="10" data-to="65" data-speed="5000" data-refresh-interval="50">65</h1>
                            </div>
                            <div class="fix charity-text pl-20">
                                <p class="text-white">Running Projects</p>
                            </div>
                        </div>
                    </div>                     
                </div>
            </div>
        </div>
    </div>
</section>

<!--Start Features Causes Areas-->
<section class="event-feature sec-padding">
    <div class="container">
        <div class="sec-content">
            <div class="row">
                <div class="col-sm-12 col-md-12 col-lg-12">
                    <div class="owl-carousel-1col" data-nav="true">
                        <div class="item">
                            <div class="featured-causes pr-15">
                                <div class="row bg-f7">
                                    <div class="col-xs-12 col-sm-6 pr-15 pl-15 p-0">
                                        <div class="thumb">
                                            <img class="full-width" src="/assets/images/causes/clist-1.jpg" alt="">
                                        </div>
                                    </div>
                                    <div class="col-xs-12 col-sm-6">
                                        <div class="causes-details">
                                            <h4 class="mb-0">Features Causes</h4>
                                            <h3>Charity For Education</h3>
                                            <ul class="list-inline">
                                                <li>Raised: $7890</li>
                                                <li class="text-thm">Goal: $9300</li>
                                            </ul>
                                            <div class="causes-progress">
                                                <div class="progress-item">
                                                    <div class="progress" data-value="85">
                                                        <div class="progress-bar" role="progressbar" aria-valuenow="85" aria-valuemin="0" aria-valuemax="100">
                                                            <div class="value-holder"><span class="value"></span>%</div>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                            <p class="p-title">Lorem ipsum dolor sit amet, consectet adipisicing elit. Sed ullam sequi at.</p>
                                            <p class="mb-0">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sint, quibusdam qui sequi ullam minima saepe, aliquid suscipit explicabo asperiores nesciunt. Diques ipsum dolor sit amet, consectetur adipisicing elit. Sint, quibusdam qui sequi ullam minima saepe,</p>
                                            <a class="thm-btn btn-xs" href="#">Donate Now</a>
                                            <a href="#" class="read-more thm-btn btn-xs btn-dark mt-0"> Read More</a>
                                        </div>
                                    </div>
                                </div>
                            </div>	            		
                        </div>
                        <div class="item">
                            <div class="featured-causes pr-15">
                                <div class="row bg-f7">
                                    <div class="col-xs-12 col-sm-6 pr-15 pl-15 p-0">
                                        <div class="thumb">
                                            <img class="full-width" src="/assets/images/causes/clist-2.jpg" alt="">
                                        </div>
                                    </div>
                                    <div class="col-xs-12 col-sm-6">
                                        <div class="causes-details">
                                            <h4 class="mb-0">Features Causes</h4>
                                            <h3>Charity For Education</h3>
                                            <ul class="list-inline">
                                                <li>Raised: $7890</li>
                                                <li class="text-thm">Goal: $9300</li>
                                            </ul>
                                            <div class="causes-progress">
                                                <div class="progress-item">
                                                    <div class="progress" data-value="90">
                                                        <div class="progress-bar" role="progressbar" aria-valuenow="90" aria-valuemin="0" aria-valuemax="100">
                                                            <div class="value-holder"><span class="value"></span>%</div>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                            <p class="p-title">Lorem ipsum dolor sit amet, consectet adipisicing elit. Sed ullam sequi at.</p>
                                            <p class="mb-0">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sint, quibusdam qui sequi ullam minima saepe, aliquid suscipit explicabo asperiores nesciunt. Diques ipsum dolor sit amet, consectetur adipisicing elit. Sint, quibusdam qui sequi ullam minima saepe,</p>
                                            <a class="thm-btn btn-xs" href="#">Donate Now</a>
                                            <a href="#" class="read-more thm-btn btn-xs btn-dark mt-0"> Read More</a>
                                        </div>
                                    </div>
                                </div>
                            </div>	            		
                        </div>
                        <div class="item">
                            <div class="featured-causes pr-15">
                                <div class="row bg-f7">
                                    <div class="col-xs-6 col-sm-6 pr-15 pl-15 p-0">
                                        <div class="thumb">
                                            <img class="full-width" src="/assets/images/causes/clist-3.jpg" alt="">
                                        </div>
                                    </div>
                                    <div class="col-xs-6 col-sm-6">
                                        <div class="causes-details">
                                            <h4 class="mb-0">Features Causes</h4>
                                            <h3>Charity For Education</h3>
                                            <ul class="list-inline">
                                                <li>Raised: $7890</li>
                                                <li class="text-thm">Goal: $9300</li>
                                            </ul>
                                            <div class="causes-progress">
                                                <div class="progress-item">
                                                    <div class="progress" data-value="90">
                                                        <div class="progress-bar" role="progressbar" aria-valuenow="90" aria-valuemin="0" aria-valuemax="100">
                                                            <div class="value-holder"><span class="value"></span>%</div>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                            <p class="p-title">Lorem ipsum dolor sit amet, consectet adipisicing elit. Sed ullam sequi at.</p>
                                            <p class="mb-0">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sint, quibusdam qui sequi ullam minima saepe, aliquid suscipit explicabo asperiores nesciunt. Diques ipsum dolor sit amet, consectetur adipisicing elit. Sint, quibusdam qui sequi ullam minima saepe,</p>
                                            <a class="thm-btn btn-xs" href="#">Donate Now</a>
                                            <a href="#" class="read-more thm-btn btn-xs btn-dark mt-0"> Read More</a>
                                        </div>
                                    </div>
                                </div>
                            </div>	            		
                        </div>
                    </div>
                </div>
            </div>				
        </div>
    </div>
</section>

<!--Blog Section-->
<section class="blog-section pt-60 pb-30" data-bg-color="#f7f7f7">
    <div class="container">
        <div class="sec-title mb-40">
            <div class="row">
                <div class="col-md-6 col-md-offset-3">
                    <span class="double-line"></span> &ensp; <h2>Latest From Our Blog</h2> &ensp; <span class="double-line"></span>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Excepturi.</p>
                </div>
            </div>	        	
        </div>

        <div class="sec-content">
            <div class="row clearfix">
                <div class="owl-carousel-3col">
                    <!--Blog Post-->
                    <div class="item featured-blog-post wow fadeInLeft" data-wow-delay="0ms" data-wow-duration="1500ms">
                        <article class="inner-box hvr-float-shadow">
                            <figure class="image">
                                <a href="blog-details.html"><img src="/assets/images/blog/1.jpg" alt=""></a>
                            </figure>
                            <div class="post-lower">
                                <div class="post-header">
                                    <div class="date"><span class="day">18</span><br>APR</div>
                                    <h3 class="title"><a href="blog-details.html">Blog post with image</a></h3>
                                    <ul class="post-info fs-13 pl-0">
                                        <li><span class="icon fa fa-user"></span> <a href="#">Jonathan Doe</a></li>
                                        <li><span class="icon fa fa-tag pl-5"></span> <a href="#">CEO Village</a></li>
                                    </ul>
                                </div>
                                <div class="post-desc">
                                    <p>Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam era...</p>
                                    <div class="text-right">
                                        <a href="blog-details.html" class="text-thm fs-14">Read more <i class="fa fa-caret-right"></i></a>
                                    </div>
                                </div>
                            </div>
                        </article>
                    </div>

                    <!--Blog Post-->
                    <div class="item featured-blog-post wow fadeInLeft" data-wow-delay="300ms" data-wow-duration="1500ms">
                        <article class="inner-box hvr-float-shadow">
                            <figure class="image">
                                <a href="blog-details.html"><img src="/assets/images/blog/2.jpg" alt=""></a>
                            </figure>
                            <div class="post-lower">
                                <div class="post-header">
                                    <div class="date"><span class="day">15</span><br>APR</div>
                                    <h3 class="title"><a href="blog-details.html">Blog post with image</a></h3>
                                    <ul class="post-info fs-13 pl-0">
                                        <li><span class="icon fa fa-user"></span> <a href="#">Jonathan Doe</a></li>
                                        <li><span class="icon fa fa-tag pl-5"></span> <a href="#">CEO Village</a></li>
                                    </ul>
                                </div>
                                <div class="post-desc">
                                    <p>Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam era...</p>
                                    <div class="text-right">
                                        <a href="blog-details.html" class="text-thm fs-14">Read more <i class="fa fa-caret-right"></i></a>
                                    </div>
                                </div>
                            </div>
                        </article>
                    </div>

                    <!--Blog Post-->
                    <div class="item featured-blog-post wow fadeInLeft" data-wow-delay="600ms" data-wow-duration="1500ms">
                        <article class="inner-box hvr-float-shadow">
                            <figure class="image">
                                <a href="blog-details.html"><img src="/assets/images/blog/3.jpg" alt=""></a>
                            </figure>
                            <div class="post-lower">
                                <div class="post-header">
                                    <div class="date"><span class="day">09</span><br>APR</div>
                                    <h3 class="title"><a href="blog-details.html">Blog post with image</a></h3>
                                    <ul class="post-info fs-13 pl-0">
                                        <li><span class="icon fa fa-user"></span> <a href="#">Jonathan Doe</a></li>
                                        <li><span class="icon fa fa-tag pl-5"></span> <a href="#">CEO Village</a></li>
                                    </ul>
                                </div>
                                <div class="post-desc">
                                    <p>Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam era...</p>
                                    <div class="text-right">
                                        <a href="blog-details.html" class="text-thm fs-14">Read more <i class="fa fa-caret-right"></i></a>
                                    </div>
                                </div>
                            </div>
                        </article>
                    </div>	            		
                </div>	                
            </div>
        </div>
    </div>
</section>